[package]
name = "fetch_edge_driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
reqwest = { version = "*", features = ["blocking"] }
bytes = "*"